### ISSUE TITLE
Time reversal example

### ISSUE THREAD

**Issue by hhapk** [waltsims/k-wave-python#122]
Hi Walter,
Thank you for your fascinating work on implying k-wave in python.  
But when i want to use k-wave-python to produce some images, I found it is not esay. The examples of k-wave in matlab can't be applied directly in your project. Because there are much difference between your work and k-wave in matlab. 
So I expect that your could **add complete examples**, not only a part. Especially, 2D  photoacoustic reconstrction.
Thanks a lot!

**Comment by hhapk** [comment]
Thank you for reply.
But I want to know how I can reconstruct the initial image after simulation, like rconstructing the po_recon in k-wave (matlab).
"sensor_data" in test_pr_2D_TR_circular_sensor.py is true bool, not "sensor_data" 70x1019 double in k-wave (matlab).
![image](https://github.com/waltsims/k-wave-python/assets/59441535/58d74bf9-9b44-4082-92d2-50fbbcce5f90)

**Comment by Jelly954** [comment]
> 感谢您的回复。但我想知道如何在仿真后重建初始图像，例如在 k-wave （matlab） 中重建po_recon。 test_pr_2D_TR_circular_sensor.py 中的“sensor_data”是真正的布尔值，而不是 K-Wave （MATLAB） 中的“sensor_data”70x1019 双精度。 ![image](https://private-user-images.githubusercontent.com/59441535/271935690-58d74bf9-9b44-4082-92d2-50fbbcce5f90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwOTYyMDEsIm5iZiI6MTcyMDA5NTkwMSwicGF0aCI6Ii81OTQ0MTUzNS8yNzE5MzU2OTAtNThkNzRiZjktOWI0NC00MDgyLTkyZDItNTBmYmJjY2U1ZjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDEyMjUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhZmJjZjE4N2VmZDAwZjlhNTE5ZTJhNGJhNzQ0NDY5MjdlN2U4MmMzYTZlMjc4MThjZGZjODY3Mzg5OGQyZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cr8xW7HjNU8wSjB4QcdqIr90QtkmzDlG4tyHIRjzzq8)

你好，请问方便加一下联系方式讨论吗？我也需要时间反演的样例，但是我并没有在test_pr_2D_TR_circular_sensor.py中找到反演重建图像的过程。

**Comment by Jelly954** [comment]
Thank you for your reply. I will continue to learn and discuss the usage of kwave. Thank you again for your research on kwavePython.

---- Replied Message ----
| From | Walter ***@***.***> |
| Date | 07/04/2024 22:37 |
| To | ***@***.***> |
| Cc | Jelly954 ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [waltsims/k-wave-python] Time reversal example (Issue #122) |

Hey @Jelly954,

The time reversal example is still not supported. Please join the discord (link on the main readme) if you'd like to discuss further.
