### ISSUE TITLE
Possible integration within the IPASC standardised image reconstruction project

### ISSUE THREAD

**Issue by jgroehl** [waltsims/k-wave-python#13]
Hey there,

Within the standardised image reconstruction project of the international photoacoustic standardisation consortium (IPASC) we were looking for a way to use the k-wave provided time reversal algorithm for image reconstruction from Python without having to invoke MATLAB.

https://github.com/IPASC/standardised-image-reconstruction

It seems that this project might be a solution to our problem. Fantastic! Either I or someone else from the project group will take a look in the next few weeks. It would be great if we could approach you with any questions we may have.

Kind regards,
Janek

**Comment by jgroehl** [comment]
It is an open project, so in case you'd be interested to join the project (e.g. regarding https://github.com/IPASC/standardised-image-reconstruction/issues/10), please let me know 😄

**Comment by waltsims** [comment]
Sounds great! We are currently still actively developing so if you find anything that doesn't quite work let us know. Also feel free to join our [telegram development group](https://t.me/+ILL4yGgcX0A2Y2Y6).

**Comment by waltsims** [comment]
Hey Janek, 

are you going to move forward with the integration? Can I close this for now?

**Comment by jgroehl** [comment]
Yes we are moving forward @waltsims. Progress is quite slow though. We've gotten the python tool to talk to the binaries 🎉 but we have not yet managed to successfully run time reversal with it.
I'll post some questions once I know what's going on :)

Is there any chance you happen to have an example where you tested time reversal already?

It is really great that this python adapter to the binaries exists! Many thanks for making it openly available!

**Comment by waltsims** [comment]
Glad you find this project useful! Many of the examples from the k-wave project have been re-implemented to test this project for correctness and can be found [here](https://github.com/waltsims/k-wave-python/tree/added_testing/tests). 

Specifically, the time reversal examples, like[ this one](https://github.com/waltsims/k-wave-python/blob/added_testing/tests/test_pr_2D_TR_circular_sensor.py), might be of interest to you, with the one caveat that the reconstruction code has not been implemented but found [here](http://www.k-wave.org/documentation/example_pr_2D_tr_circular_sensor.php). I hope this helps for now! If you complete the examples, feel free to create a pull request to contribute! :)

**Comment by waltsims** [comment]
Hey Janek,

I'm going to close this for now. Feel free to re-open this issue in the future if there is more progress and a PR!

Best,
-Walter
