### ISSUE TITLE
`SimulationExecutionOptions` is not in kwave.options anymore

### ISSUE THREAD

**Issue by astanziola** [waltsims/k-wave-python#135]
Hello team! I was playing with a fresh install and following the example, however I believe that this line is not correct anymore?

https://github.com/waltsims/k-wave-python/blob/12db9efda690aa552adf99c692ae9589651e27f6/examples/bmode_reconstruction_example.py#LL6C52-L6C52

I don't see `SimulationExecutionOptions` in `kwave.options` anymore. 

Related to this, I believe that the entire `kwave.options` module failed to render in the documentation: https://waltersimson.com/k-wave-python/kwave.options.html

Thanks for the great work again!

**Comment by yfarid-lilt** [comment]
Hey Antonio! The behavior you experience is a bit unexpected. We still have the `SimulationExecutionOptions` in `kwave.options` (see [here](https://github.com/waltsims/k-wave-python/blob/master/kwave/options/__init__.py)).

When you say "fresh install", do you mean installation from the latest release? If so, the example relies on the latest state of the `main` branch. We did not make a new release with the latest changes yet.

Also, regarding the documentation, thanks for bringing this up! We will check it this week and try to fix.

**Comment by astanziola** [comment]
Yes, it was a pip install from the release, my bad, sorry for the useless issue 😄

**Comment by faridyagubbayli** [comment]
Great! Thank you for the issue -- it emphasizes need for a better versioning! (cc @waltsims)
