### ISSUE TITLE
`kspaceFirstOrder3D` always run on GPU, even when `kspaceFirstOrder3DC` is called

### ISSUE THREAD

**Issue by guillaumedavidphd** [waltsims/k-wave-python#159]
Thanks for this Python re-implementation of the k-wave interface! I noticed that the code always calls k-wave's GPU binary regardless of whether `kspaceFirstOrder3DC` or `kspaceFirstOrder3DG` is used. This is due to the below line in `kspaceFirstOrder3D`. Is this expected behavior?

https://github.com/waltsims/k-wave-python/blob/d9558440eba825fc1e79e51d3e78b2a562e2c352/kwave/kspaceFirstOrder3D.py#L464

**Comment by waltsims** [comment]
Hey, yes, currently, this is expected behavior. I'm happy to leave this issue open until we update kspaceFirstOrder3D{C,G}. If you want to take a stab at it, we welcome a PR.
