### ISSUE TITLE
First Windows User

### ISSUE THREAD

**Issue by Redstonemaster29** [waltsims/k-wave-python#18]
It would be awesome if this worked on windows!

**Comment by ktritz** [comment]
I got it working on windows by modifying executor.py as follows:

in __init__
comment out/delete the if not self._is_linux / raise NotImplementedError

after the if device == 'gpu' / 'cpu' blocks add:
        if binary_folder == 'windows':
            binary_name += '.exe'

in run_simulation, replace the env_variables up through command = ... with the following:

        env_variables = {
            'LD_LIBRARY_PATH': '',
            'OMP_PLACES': 'cores',
            'OMP_PROC_BIND': 'SPREAD',
        }
        os.environ.update(env_variables)
        
        command = f'{self.binary_path} -i {input_filename} -o {output_filename} {options}'

that's it so far

**Comment by ktritz** [comment]
Submitted a pull request with the changes.
