### ISSUE TITLE
log_compression() units

### ISSUE THREAD

**Issue by benfrey** [waltsims/k-wave-python#182]
What are the units for parameter "cf"? I found this to not be clear in the k-wave MATLAB version either.

Typically, a compression factor on the scale (0,1] is used in ultrasound from my understanding.

Thank you

**Comment by waltsims** [comment]
The compression factor is unitless.

Log compression is comparable to [gamma correction in natural images](https://en.wikipedia.org/wiki/Gamma_correction). I'm not sure where the formulation from the k-Wave package comes from, but in general, there is no standard functional description and many scanners have custom function curves.
