### ISSUE TITLE
v1.4.0 Example: Defining A Sensor Using An Array Transducer

### ISSUE THREAD

**Issue by faridyagubbayli** [waltsims/k-wave-python#183]

**Comment by waltsims** [comment]
pleas look at some of the changes on my example branch. They might be helpful for you as well.

**Comment by waltsims** [comment]
Currently, this example cannot run with the compiled executables because it uses a cartesian definition of sensor mask which is not correctly converted to sensor_grid before calling the executables.

see line 616 of kspaceFirstOrder_inputchecking in Matlab.
