### ISSUE TITLE
cart2grid function

### ISSUE THREAD

**Issue by bvale1** [waltsims/k-wave-python#191]
Does k-wave-python include an equivalent function to the cart2grid function from MATLAB k-wave?
e.g. in MATLAB:
`sensorxz = makeCartCircle(radius, nsensor, centre, arc);`
`sensor.mask = cart2grid(kgrid, sensorxz);`

Happy to write this function for k-wave-python and submit a pull request if it doesn't exist yet

**Comment by faridyagubbayli** [comment]
We do have an implementation of `cart2grid` in Python. Please have a look [here for the implementation](https://github.com/waltsims/k-wave-python/blob/88541d092afadd97c67ebd3710de965fd8ac14e8/kwave/utils/conversion.py#L152) and [here for the test](https://github.com/waltsims/k-wave-python/blob/88541d092afadd97c67ebd3710de965fd8ac14e8/tests/matlab_test_data_collectors/python_testers/cart2grid_test.py#L11). In case you identify some edge cases that are not handled, we're more than happy to have a PR to review :)
