### ISSUE TITLE
No "add_custom_element" function in kWaveArray

### ISSUE THREAD

**Issue by bvale1** [waltsims/k-wave-python#208]
There appears to be no "add_custom_element" function in the kWaveArray class which should allow the user to define their own integration points for a custom array element

**Comment by bvale1** [comment]
I've added this function in my own branch of k-wave-python and started using it, happy to write a test as well and submit a pull request :)

**Comment by waltsims** [comment]
Hey!

Thanks for looking into this. A PR would be great. Just in time for our planned v0.3.0 release.

Best,
Walter

**Comment by bvale1** [comment]
I've added a few lines to KWaveArray_test.py that should test the add_custom_element function but I'm not entirely sure how to run the tests, could you assist?

**Comment by bvale1** [comment]
Hi Walter,

I've written a couple of cases (one for 2d and one for 3d) I've just had some issues running them, I changed the Dockerfile from 'COPY README.md .' to 'COPY docs docs/' in order to build it on my machine. I currently have a problem running the collectors in MATLAB 'unrecognized function or variable focusedBowlONeil'. I can have another crack at it tomorrow :)

Best wishes,
Billy.

**Comment by waltsims** [comment]
Thanks for updating the DockerFile. I last used it quite some time ago. Please add those changes to your PR!

**Comment by waltsims** [comment]
closed with #212
