### ISSUE TITLE
Bug in kwave.utils.conversion.tol_star when using 1d or 2d sensor kwave_array

### ISSUE THREAD

**Issue by bvale1** [waltsims/k-wave-python#220]
In the off_grid_points function from kwave_array.py:
```
        else:
            # create an array of neighbouring grid points for BLI evaluation
            if kgrid.dim == 1:
                ind, is_ = tol_star(bli_tolerance, kgrid, point, debug)
                xs = x_vec[is_]
                xyz = xs
            elif kgrid.dim == 2:
                ind, is_, js = tol_star(bli_tolerance, kgrid, point, debug)
                xs = x_vec[is_]
                ys = y_vec[js]
                xyz = np.array([xs, ys]).T
            elif kgrid.dim == 3:
                ind, is_, js, ks = tol_star(bli_tolerance, kgrid, point, debug)
```
It 2 values are expected from tol_star when kgrid.dim is 1 ect...
In tol_star from line 449:
```
    if kgrid_dim == 1:
        lin_ind = is_
    elif kgrid_dim == 2:
        lin_ind = kgrid.Nx * (js - 1) + is_
    elif kgrid_dim == 3:
        lin_ind = kgrid.Nx * kgrid.Ny * (ks - 1) + kgrid.Nx * (js - 1) + is_

    return lin_ind, is_ - 1, js - 1, ks - 1  # -1 for mapping from Matlab indexing to Python indexing
```
Four values are always returned which causes an error in the 2d and 1d cases, happy to submit a pr to fix :)

best wishes,
Billy.

**Comment by waltsims** [comment]
Hey,

Good find! Currently, tol_star does not have test coverage. A PR on this would be very welcome, and if you could include a MATLAB collector with respective pytests for test coverage as well, that would be great.

Thanks,
Walter

**Comment by waltsims** [comment]
Hey Billy,

I have made some changes to tol_star in #193 that still are under review. It would be best to base your changes off of that branch since I expect them to be merged into main this week.

Best,
Walter

**Comment by bvale1** [comment]
Hi Walter,

I notice you have already fixed the bug in this branch by ignoring some of the return values in the ```off_grid_points``` function!
e.g.
```
if kgrid.dim == 1:
                ind, is_, _, _ = tol_star(bli_tolerance, kgrid, point, debug)
                xs = x_vec[is_]
                xyz = xs
```
So as soon as these changes are merged I would say this issue should be resolved. Sadly I don't think will have time to write the tests and data collectors for tol_star anytime soon due to my own projects.

Best wishes,
Billy.

**Comment by bvale1** [comment]
I take it back, there is a bit more needed to fix the kwavearray in 2d, e.g. ```is_``` and ```js_``` need to be cast to integers as in the 3d case.

I can pr my fixes once my 2d time reversal is working, but I won't be testing the 1d case.

**Comment by bvale1** [comment]
@waltsims works for me, I'd say this issue is resolved.

**Comment by waltsims** [comment]
Great. We also now have test coverage, thanks to @faridyagubbayli.
