### ISSUE TITLE
[BUG] Phantom data cannot be downloaded from google drive

### ISSUE THREAD

**Issue by waltsims** [waltsims/k-wave-python#250]
**Describe the bug**
When attempting to download the phantom data from the b-mode example, I get the following error.

```
FileNotFoundError: [Errno 2] No such file or directory: 'phantom_data.mat'
```

**Expected behavior**
Of course the download link should work propperly

**Desktop (please complete the following information):**
 - OS: linux
 - Version: commit bbe79cc30b24ef7ea9eab404fdffed466e565b58

**Comment by faridyagubbayli** [comment]
I think we face the issue described here: https://github.com/wkentaro/gdown/issues/43#issuecomment-1782110461

As a temporary solution, we can duplicate the file and update the `phantom_data`'s link. Eventually we need to find a new place to host this data.

**Comment by waltsims** [comment]
One option could be creating a Github release to host this data, though it is not the cleanest solution. I would be open to other options.

**Comment by faridyagubbayli** [comment]
I like the idea! If there are no other cleaner and "easy to achieve" solution, I vote for the above idea.

**Comment by waltsims** [comment]
It seems [4.6.4 was the issue](https://github.com/wkentaro/gdown/issues/292#issuecomment-1888763342) so downgrading fixed the issue for now.
