### ISSUE TITLE
Migrate examples to jupytext

### ISSUE THREAD

**Issue by waltsims** [waltsims/k-wave-python#254]
**Is your feature request related to a problem? Please describe.**

It is hard to keep example python files synchronize with ipython notebooks

**Describe the solution you'd like**
Jupytext with with [pre-commit hook](https://jupytext.readthedocs.io/en/latest/using-pre-commit.html) to synchronize ipython notebooks might be a solution

**Comment by faridyagubbayli** [comment]
Great idea! Let's dive into a deeper discussion in our next weekly discussion meeting.
