### ISSUE TITLE
Add CITATION.cff

### ISSUE THREAD

**Issue by bvale1** [waltsims/k-wave-python#255]
I'd like to cite k-wave-python (as well as k-wave) in future publications. I just read this can be done by adding a CITATION.cff file to the repo people will be able to generate citations in the APA or BibTeX formats:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Comment by waltsims** [comment]
It looks like we can [create a DOI with Zenedo](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content). I will look into this.
