### ISSUE TITLE
WARNING:root:kspaceFirstOrder-OMP at_array_as_sensor.ipynb

### ISSUE THREAD

**Issue by waltsims** [waltsims/k-wave-python#256]
**Describe the bug**
When importing kwave in [examples/at_array_as_sensor/at_array_as_sensor.ipynb](https://github.com/waltsims/k-wave-python/pull/229/files/991c891aa8493e66ec4bc12efb098eb6f018b9d8#diff-de70b7d5b53423380864a279d9108b527be99c26ad6fa3306fdb6f21c0f252b7) the users is warned that a binary is not found.

**To Reproduce**

```python
import kwave.data
```

**Expected behavior**
The binaries are expected to be properly installed upon the first execution of the program.

**Comment by serieslover** [comment]
The Warning keeps! after _import kwave.data_.
And then error occurs, which show timeoutError without response from the host/peer.

**Comment by faridyagubbayli** [comment]
@serieslover 

Can you share info about your setup? For example, Python & OS versions, kWave version and how you installed it and etc.

> And then error occurs, which show timeoutError without response from the host/peer.

Can this be due to slow network connectivity?
