### ISSUE TITLE
Publish package

### ISSUE THREAD

**Issue by faridyagubbayli** [waltsims/k-wave-python#3]
Publish package to PyPI and update the installation guide in Readme.

**Comment by waltsims** [comment]
pypi currently has a package size limit of 100 MB. This is problematic with the current "ship all the binaries" approach. Looking for a solution.

**Comment by waltsims** [comment]
even without windows binaries, the package is currently ~150 MB

**Comment by waltsims** [comment]
[These](https://www.dampfkraft.com/code/distributing-large-files-with-pypi.html) look to be our options. We have discussed all before but just wanted to note them here. Further, we could ship the source code as a dependency and install locally as previously discussed.

**Comment by waltsims** [comment]
I filed a request to increase the max file size [here](https://github.com/pypa/pypi-support/issues/1890).

**Comment by waltsims** [comment]
The accepted a package size of 300 MB. We should try to solve this in future releases to reduce the package size.

**Comment by waltsims** [comment]
long story short. MANIFEST.in does not include the binaries in the .whl for package. Updated setup.py accordingly now to package correctly.
