### ISSUE TITLE
[BUG] Typing for make_cart_spherical_segment

### ISSUE THREAD

**Issue by djps** [waltsims/k-wave-python#307]
**Describe the bug**
The strict typing breaks an example on a branch which was working that I wanted to push. 

When I try to add an annular array, an error appears from `make_cart_spherical_segment` as the bowl_position should be an int, previously it was only need to be list-like.

**Expected behavior**
 I think the bowl_position should be `NDArray[Shape['3'], Float]` as this would also be consistent with the documentation which specifies that the units are metres.

**Comment by waltsims** [comment]
I agree as described **here**. Can you please create a failing test and update the code for it to pass?
