### ISSUE TITLE
[BUG] Two times log compression in the example: us_bmode_linear_transducer

### ISSUE THREAD

**Issue by Felixduelmer** [waltsims/k-wave-python#310]
**Describe the bug**
In the example code for simulating the linear transducer in US imaging, the log compression is applied two times:
1. in the Log Compression cell:
```
compression_ratio = 3
scan_lines_fund = log_compression(scan_lines_fund, compression_ratio, True)
scan_lines_harm = log_compression(scan_lines_harm, compression_ratio, True)  
```
2. in the visualization code:
```
harm_img = db(scan_lines_harm.T)
fund_img = db(scan_lines_fund.T)
```
This is probably not intended and should be removed.

**Expected behavior**
I expect only one log compression to happen during the postprocessing steps.

**Comment by faridyagubbayli** [comment]
@Felixduelmer seems log compression is applied to different variables though. First time it is applied to the `scan_lines_fund` while second time it is applied to the `scan_lines_harm`. Furthermore, the same logic is found in the Matlab-version of the same example (see [these two lines](https://github.com/ucl-bug/k-wave/blob/2d9801217575b6d50ff1b79e9355713c470719ac/k-Wave/examples/example_us_bmode_linear_transducer.m#L339-L340)). Is there anything I'm missing?

**Comment by Felixduelmer** [comment]
Thanks, @faridyagubbayli for your reply. 
In the examples, the log_compression is applied to both scan lines (fundamental and harmonic), which I think is correct. But additionally, in the visualization part, the scan lines are converted to db due to the call to [db()](https://github.com/waltsims/k-wave-python/blob/15ce6205e070918ee6a2c324d9aa0ff146f9099e/examples/us_bmode_linear_transducer/us_bmode_linear_transducer.py#L235C1-L236C37) .
In this [function](https://github.com/waltsims/k-wave-python/blob/15ce6205e070918ee6a2c324d9aa0ff146f9099e/kwave/reconstruction/tools.py#L24C1-L25C36), the log-compressed data would than again be log-compressed: 
`def db(x):
    return 20 * np.log10(np.abs(x))` 
So yes, I think the log compression should be applied to both variables: `scan_lines_fund` and `scan_lines_harm`, but this db call in the visualization code should not be there and is also missing in the original example as far as I can tell.

**Comment by faridyagubbayli** [comment]
Ahh I see now @Felixduelmer, thank you for the clarification!
