### ISSUE TITLE
meta data file for lazy installation

### ISSUE THREAD

**Issue by faridyagubbayli** [waltsims/k-wave-python#321]

**Comment by faridyagubbayli** [comment]
@waltsims what kind of metadata are we talking about here? Is it about the file hashes?

**Comment by waltsims** [comment]
We were talking about the file URL's I believe.

**Comment by waltsims** [comment]
The file lists, base urls and file locations, though some refactoring might simplify things:

https://github.com/waltsims/k-wave-python/blob/master/kwave/__init__.py

**Comment by faridyagubbayli** [comment]
Local files are not versioned. If we have new release version, we will be unable to re-download files. Metadata file will help to detect when a new release is available.
