### ISSUE TITLE
Use jaxtyping for typing

### ISSUE THREAD

**Issue by faridyagubbayli** [waltsims/k-wave-python#350]
Recently, we added typing and type checks using `nptyping` and `beartype`. Seems `nptyping` is not maintened (last commit was about 1 year ago). We should switch `jaxtyping` instead.

Initially we didn't go with `jaxtyping` because I thought `jaxtyping` will add `jax` as dependency to the project. Seems this is not the case and we can use it.

**Comment by bvale1** [comment]
Currently experiencing an issue which might be related to ```nptyping``` although I'm not entirely sure. Trying to use the function ```cart2grid``` from ```conversion.py``` with the type hint :
```
cart_data: Union[
                  NDArray[Shape["1, NumPoints"], Float], NDArray[Shape["2, NumPoints"], Float], NDArray[Shape["3, NumPoints"], Float],
]
```
After trying various inputs I can't seem to satisfy this:
printing the type, shape ect. for my input ```cart_data: <class 'numpy.ndarray'>, (2, 512), float32. [[-0.02890019 -0.02915836 -0.02941653 ...  0.02941654  0.02915836   0.02890019]```

When passing this into the cart2grid it throws back an exception:
```
File "<@beartype(kwave.utils.conversion.cart2grid) at 0x7fe85c813010>", line 44, in cart2grid
beartype.roar.BeartypeCallHintParamViolation: Function kwave.utils.conversion.cart2grid() parameter cart_data="array([[-0.02890019, -0.02915836, -0.02941653, ...,  0.02941654,
         0.02915836,  0.0...)" violates type hint typing.Union[nptyping.ndarray.NDArray, nptyping.ndarray.NDArray, nptyping.ndarray.NDArray], as <protocol "numpy.ndarray"> "array([[-0.02890019, -0.02915836, -0.02941653, ...,  0.02941654,
         0.02915836,  0.0...)" not <class "nptyping.ndarray.NDArray">, <class "nptyping.ndarray.NDArray">, or <class "nptyping.ndarray.NDArray">
```
I can't see anything wrong with my input, so hopefully the switch to jaxtyping will fix this.

**Comment by faridyagubbayli** [comment]
@bvale1 the issue you face is very weird. Now that jaxtyping PR is merged, I wonder if you had chance to check if that fixed your issue?

**Comment by bvale1** [comment]
Just tested this out with the latest version which uses jaxtyping, I can confirm my (exact) same input as before now works perfectly! I'm pretty the problem before was related to nptyping.
