### ISSUE TITLE
[BUG] Question about exponentially increasing pressure when adding heterogenous density

### ISSUE THREAD

**Issue by ivanmkc** [waltsims/k-wave-python#353]
**Describe the bug**
In some situations, adding heterogenous density results in greatly increasing pressure.

I'm new to ultrasound and k-wave so perhaps this is user error.

**To Reproduce**
See attached notebook.

Adding a tiny area of heterogenous density is enough to reproduce this behaviour.

[Ultrasound_Simulation_2D_(k_wave_python) (1).ipynb.zip](https://github.com/waltsims/k-wave-python/files/14736742/Ultrasound_Simulation_2D_.k_wave_python.1.ipynb.zip)

**Expected behavior**
I won't expect a tiny area of different density to lead to enormous increases in pressure.

**Screenshots**
Increasing pressure over time
<img width="1003" alt="Screenshot 2024-03-25 at 5 19 43 AM" src="https://github.com/waltsims/k-wave-python/assets/1586049/036bf835-a2ae-4fb0-a5c2-48e7dd56cc04">

**Desktop (please complete the following information):**

Colab

**Additional context**

**Comment by ivanmkc** [comment]
Thanks @djps. 

1. Changing `cfl` to 0.03 doesn't change anything for me fixes it for me as well.
2. check_stability returns inf regardless of if the line is commented out or not, indicating that the "model is unconditionally stable". However, the function help mentions:

```
    The time steps given are accurate when the medium properties are
    homogeneous. For a heterogeneous media they give a useful, but not
    exact, estimate.
```

I'll do more reading on how to set the cfl. Is that just a hyper-parameter to tweak and test?

**Comment by ivanmkc** [comment]
Here is some additional testing. It seems like there are variations (see the diagonal artifacts) even at lower cfl values. If anyone knows a principled way to determine the correct cfl, please let me know.

Are lower cfl values necessarily more "correct"?

<img width="1267" alt="Screenshot 2024-04-09 at 3 41 03 PM" src="https://github.com/waltsims/k-wave-python/assets/1586049/f3cacb90-ece8-439e-a878-0efad08768fc">

**Comment by waltsims** [comment]
@djps Thanks for looking into this. 

@ivanmkc Running with a CFL number of 0.03 I was able to produce stable simulations using your notebook.

Another good resource for you could be Section 2.7 of the [k-Wave manual](http://www.k-wave.org/manual/k-wave_user_manual_1.1.pdf) if you haven't already found it.
![pressure](https://github.com/waltsims/k-wave-python/assets/8669206/730a4538-5f35-45e6-930e-44c2511b0c2c)

 I hope that's helpful.

**Comment by waltsims** [comment]
Closing for now
