### ISSUE TITLE
[BUG] Binaries re-downloading on every import on Windows

### ISSUE THREAD

**Issue by peterhollender** [waltsims/k-wave-python#366]
This problem arose when moving from the 0.2.1 release to the 0.3.3 release. I noticed that every time I called `import kwave`, it would take ~45s on my computer. I expected this to happen on the first run, as k-wave needs to go grab the binaries, but I noticed that on my installation, this is happening every time, overwriting my existing binaries with identical copies. 

**To Reproduce**
Run `import kwave` or the `0.3.3` release. I injected some logging in my local copy to help debug, but the error popped up out of the box.

**Expected behavior**
During `kwave/__init__` the `url_dict` object is created.  On windows 10, if I access `kwave.url_dict` after importing, I get the following:
```
{'linux': {'cuda': ['https://github.com/waltsims/kspaceFirstOrder-CUDA-linux/releases/download/v1.3.1/kspaceFirstOrder-CUDA'],
  'cpu': ['https://github.com/waltsims/kspaceFirstOrder-OMP-linux/releases/download/v1.3.0/kspaceFirstOrder-OMP']},
 'windows': {'cuda': ['https://github.com/waltsims/kspaceFirstOrder-CUDA-windows/releases/download/v1.3.0/cufft64_10.dll',
   'https://github.com/waltsims/kspaceFirstOrder-CUDA-windows/releases/download/v1.3.0/hdf5.dll',
   'https://github.com/waltsims/kspaceFirstOrder-CUDA-windows/releases/download/v1.3.0/hdf5_hl.dll',
   'https://github.com/waltsims/kspaceFirstOrder-CUDA-windows/releases/download/v1.3.0/libiomp5md.dll',
   'https://github.com/waltsims/kspaceFirstOrder-CUDA-windows/releases/download/v1.3.0/libmmd.dll',
   'https://github.com/waltsims/kspaceFirstOrder-CUDA-windows/releases/download/v1.3.0/msvcp140.dll',
   'https://github.com/waltsims/kspaceFirstOrder-CUDA-windows/releases/download/v1.3.0/svml_dispmd.dll',
   'https://github.com/waltsims/kspaceFirstOrder-CUDA-windows/releases/download/v1.3.0/szip.dll',
   'https://github.com/waltsims/kspaceFirstOrder-CUDA-windows/releases/download/v1.3.0/vcruntime140.dll',
   'https://github.com/waltsims/kspaceFirstOrder-CUDA-windows/releases/download/v1.3.0/zlib.dll',
   'https://github.com/waltsims/kspaceFirstOrder-CUDA-windows/releases/download/v1.3.0/kspaceFirstOrder-CUDA.exe'],
  'cpu': ['https://github.com/waltsims/kspaceFirstOrder-OMP-windows/releases/download/v1.3.0/cufft64_10.dll',
   'https://github.com/waltsims/kspaceFirstOrder-OMP-windows/releases/download/v1.3.0/hdf5.dll',
   'https://github.com/waltsims/kspaceFirstOrder-OMP-windows/releases/download/v1.3.0/hdf5_hl.dll',
   'https://github.com/waltsims/kspaceFirstOrder-OMP-windows/releases/download/v1.3.0/libiomp5md.dll',
   'https://github.com/waltsims/kspaceFirstOrder-OMP-windows/releases/download/v1.3.0/libmmd.dll',
   'https://github.com/waltsims/kspaceFirstOrder-OMP-windows/releases/download/v1.3.0/msvcp140.dll',
   'https://github.com/waltsims/kspaceFirstOrder-OMP-windows/releases/download/v1.3.0/svml_dispmd.dll',
   'https://github.com/waltsims/kspaceFirstOrder-OMP-windows/releases/download/v1.3.0/szip.dll',
   'https://github.com/waltsims/kspaceFirstOrder-OMP-windows/releases/download/v1.3.0/vcruntime140.dll',
   'https://github.com/waltsims/kspaceFirstOrder-OMP-windows/releases/download/v1.3.0/zlib.dll',
   'https://github.com/waltsims/kspaceFirstOrder-OMP-windows/releases/download/v1.3.0/kspaceFirstOrder-OMP.exe']}}
```

During the calls to `_is_binary_present("kspaceFirstOrder-OMP.exe","cpu")` and `_is_binary_present("kspaceFirstOpder-CUDA.exe", "cuda")`, `_is_binary_present` kicks out a `False` under the "If there is a new binary" check. This happens because it checks
```
    latest_url = url_dict[system][binary_type][0]
    if existing_metadata['url'] != latest_url:
        return False
```
But we know exactly what `url_dict` was, because it was created higher up in the code, and we can see that `url_dict['windows']['cpu'][0]` is the _first_ element of the list, which is the url for `cufft64_10.dll`, not `kspaceFirstOrder-OMP.exe`. 

I think that we should change lines 121 and 122 to:
```
    latest_urls = url_dict[system][binary_type]
    if existing_metadata['url'] not in latest_urls:
```

This will let `_is_binary_present` verify that the installed url is within the list rather than checking against the first element, which seems to only be valid for linux's DLL-free, one-element list. 

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by waltsims** [comment]
Hey Peter,

Thanks for bringing this to my attention. I'll look into it and try to fix it asap. If you have a fix before me, PR welcome 👍
