### ISSUE TITLE
Inquiry About Setting 'k_dim' or 'kgrid_dim' to 3 for kspaceFirstOrder2D Function in KWaveSimulation.py

### ISSUE THREAD

**Issue by GuilJung** [waltsims/k-wave-python#408]
Hi @waltsims 

It seems like there's an error because k_dim is set to 3 on line 952 of KWaveSimulation.py, which causes issues when you want to use the kspaceFirstOrder2D function. 

Is there a specific reason why k_dim must be set to 3, instead of kgrid_dim? 

Or is it possible that the implementation for 2D simulations isn't fully developed yet?

Thanks!

**Comment by waltsims** [comment]
Hi @GuilJung,

If your referring to this assertion, k-Wave-Transducer does not support 2D simulations. This is also the current behavior in the original k-Wave as well. Nevertheless, 2D simulations are possible in k-wave-python. The [k-Array](https://github.com/waltsims/k-wave-python/blob/master/kwave/utils/kwave_array.py) is what I would recommend to create 2D and 3D arrays.
k-Array interpolates cartesian definitions of elements onto your k-grid while minimizing aliasing.

Here are some examples of 2D simulations with k-Array:

https://github.com/waltsims/k-wave-python/tree/master/examples/at_array_as_sensor
https://github.com/waltsims/k-wave-python/blob/master/examples/at_array_as_source/at_array_as_source.py

And simulating a linear array:
https://github.com/waltsims/k-wave-python/tree/master/examples/at_linear_array_transducer

If you have any further questions let me know.

**Comment by GuilJung** [comment]
Thank you very much for your kind response.  I've been continuously trying with the examples. 

In fact, my goal is to run the existing MATLAB code exactly in kwave-Python. 

I aim to measure a 2D phantom of size 120e-3[m] x 120e-3[m] using a phased probe with the following conditions:

Center frequency=3.5MHz /  Element=80 / pitch size=0.25e-3 / Transmitting Plane waves at 5-degree intervals from -45 to 45 degrees. 

In the MATLAB code below, I used **kspaceFirstOrder2D**, which is very similar to the **kspaceFirstOrder2D.py** function in k-wave-python. 
Also, it seems similar to the **kspace_first_order_2d_gpu** function from the 2D simulation example you provided. 

Could you please advise on what examples or functions would be appropriate to run such a simulation?
I apologize if my question was too careless.

   
Example of matlab code

   steering_angle = -45:5:45;         % PLEASE CHECK ROI
   n_steering_angle = size(steering_angle,2);
   
   focus = 0e-3;
   focus_x = focus*cos(steering_angle*pi/180);
   focus_y = focus*sin(steering_angle*pi/180);
   
   d = gpuDevice(num_GPU);


   % =========================================================================
   % SIMULATION
   % =========================================================================
   % initialize
   medium = struct();
   source = struct();
   sensor = struct();

   % simulation settings
   DATA_CAST       = 'gpuArray-single';     % set to 'single' or 'gpuArray-single' to speed up computations
   RUN_SIMULATION  = true;         % set to false to reload previous results instead of running simulation

   % create the computational grid
   ROIx = 120e-3;         % ROI [m]
   ROIy = 120e-3;         % ROI [m]
   PML_size = 100;          % size of the PML in grid points
   Nx = 3000;  % number of grid points in the x (row) direction
   Ny = 3000 ;  % number of grid points in the y (column) direction
   dx = ROIx/Nx;            % grid point spacing in the x direction [m]
   dy = ROIy/Ny;            % grid point spacing in the y direction [m]

   kgrid = kWaveGrid(Nx, dx, Ny, dy);
   f0 = 3.5e6;           % Center frequency [Hz]

   % Sensor
   pitch = 0.25e-3;      % length between each sensor [m]
   kerf = 0;
   N_active_tx = 80;             % Num. of elem. of transducer

   % Vecter
   x=((0:(Nx-1))-(Nx-1)/2)*dx;   % x-vector [m]
   y=(0:(Ny-1))*dy;              % z-vector [m]

   % =========================================================================
   % DEFINE THE MEDIUM PROPERTIES
   % =========================================================================
   % define the properties of the propagation medium
   c0_exact = 1540;                  % [m/s]
   rho0 = 1000;                % [kg/m^3]
   alpha_coeff_exact = 0.5;          % [dB/(MHz^y cm)]
   lambda = c0_exact/f0;       % wavelengsth [m]

   % create the time array
   t_end = (Nx*dx)* 2.5 / c0_exact;     % [s]
   dt = 1/62.5e6/2;             % Sampling time [s]   
   cfl = (dt * c0_exact / dx);   % default : 0.3 
   kgrid.makeTime(c0_exact, cfl, t_end);

   % define a large image size to move across
   Nx_tot = Nx;
   Ny_tot = Nx;
   ROIx_tot = Nx_tot * dx;
   ROIy_tot = Ny_tot * dy;

   % =========================================================================
   % LOAD MEDIUM
   % =========================================================================
   load([data_path, load_name]);

   medium.sound_speed = medium_value.sound_speed;           % 1400 ~ 1700 [m/s]
   medium.density = medium_value.density;                   % 850 ~ 1150 [kg/m^3]
   medium.alpha_coeff = medium_value.alpha_coeff_gauss;                 % 0 ~ 1.5 [dB/MHz/cm]
   medium.alpha_power = 1.1;
   medium.BonA = 6;
   %%%
   medium_temp = medium;
   medium_temp.sound_speed_mean = medium_value.sound_speed_gauss;
   medium_temp.sound_speed_var = medium_value.sound_speed_var;
   medium_temp.scatterer_radi = medium_value.scatterer_radi;
   medium_temp.scatterer_mu = medium_value.scatterer_mu;
   medium_temp.edge_map = medium_value.edge_map;
   medium_temp.sound_speed_mean_notgauss = medium_value.sound_speed_mean;
   medium_temp.alpha_coeff_notgauss = medium_value.alpha_coeff;

   % =========================================================================
   % DEFINE THE INPUT SIGNAL
   % =========================================================================
   % define properties of the input signal
   source_strength = 1e1;       % [Pa]
   tone_burst_freq = f0;      % [Hz]
   tone_burst_cycles = 5;      % 5 is optimum
   for n_input_signal = 1:19%1:n_steering_angle
      if n_input_signal>3 && n_input_signal<17
          continue;
      end
      % Source position
      geom = [pitch*((1:N_active_tx)-(N_active_tx+1)/2).' zeros(N_active_tx,2)]; % probe's geometry
      pitch_n=round(pitch/dx);            % quantified pitch
      [dummy n0]=min(abs(x+N_active_tx*pitch/2));   % initial transducer position

      % create the input signal using toneBurst 
      num_elements = N_active_tx;
      element_index = -(num_elements - 1)/2:1:(num_elements - 1)/2;
%                tone_burst_offset = -sign(focus_x(n_input_signal)) * sqrt((pitch * element_index - focus_y(n_input_signal)).^2 + focus_x(n_input_signal).^2)/(c0_exact*dt);
      tone_burst_offset = pitch*element_index*sin(steering_angle(n_input_signal)*pi/180)/(c0_exact*dt);
      offset_time = min(tone_burst_offset);
      offset_time_max = max(tone_burst_offset);
      tone_burst_offset = -(offset_time) + tone_burst_offset;
      source.ux = (source_strength./(c0_exact*rho0)).* toneBurst(1/kgrid.dt, tone_burst_freq, ...
         tone_burst_cycles, 'SignalOffset', tone_burst_offset);

      length_source = size(source.ux,2);
      row_source = size(source.ux,1);
      time_step = size(kgrid.t_array,2);
      zero_padding = zeros(row_source,time_step-length_source);
      source.ux = [source.ux zero_padding];
      pulse_waveform = source.ux;
      source.ux = [];
      source.u_mask = zeros(Nx,Ny);

      tx_apodization = ones(N_active_tx,1);
      if rem(pitch_n,2) == 0
         pitch_n_temp = pitch_n-1;
      else
         pitch_n_temp = pitch_n;
      end
      for n=1:N_active_tx
         pulse_waveform_n = pulse_waveform(n,:);
         source_y_pos = round(Ny/2) - round((pitch/ROIy*Ny) * ((N_active_tx+1)/2-n));
         nx = [round(source_y_pos-(pitch_n_temp-1)/2) :round(source_y_pos+(pitch_n_temp-1)/2)  ];
         ny = 1;
         source.u_mask(ny,nx)=1;
         source.ux=[source.ux; repmat(tx_apodization(n)*pulse_waveform_n,pitch_n_temp,1)   ];
      end  


      % =========================================================================
      % RUN THE SIMULATION
      % =========================================================================

      % define a binary line sensor
      sensor.mask=source.u_mask;

      % set the input arguements: force the PML to be outside the computational
      input_args = {...
         'PMLInside', false, 'PMLSize', PML_size, ...
         'DataCast', DATA_CAST, 'DataRecast', true, 'PlotSim', false};

      sensor_data = kspaceFirstOrder2D(kgrid, medium, source, sensor, input_args{:});
      p_sensor_data=permute(sensor_data,[2 1]);

      % converting sensir data to channel data
      rf_channel_data=zeros(size(p_sensor_data,1),N_active_tx);
      for n=1:N_active_tx
         rf_channel_data(:,n)=rf_channel_data(:,n)+sum(p_sensor_data(:,pitch_n_temp*(n-1)+(1:pitch_n_temp)),2);
      end
      rf_channel_data_tot(:, :, n_input_signal) = rf_channel_data;
   end

**Comment by waltsims** [comment]
Hey @GuilJung,

when running your example, I found a bug I fixed in #411.

I can run your example but will perform further tests before sharing here.

**Comment by GuilJung** [comment]
Hello @waltsims 

Thank you for checking. I'll be waiting for you to share the results.

**Comment by waltsims** [comment]
Hi @GuilJung,

this code runs, but since the domain is empty there are no reflections.

```python
import numpy as np
from kwave.data import Vector
from kwave.kgrid import kWaveGrid
from kwave.kmedium import kWaveMedium
from kwave.ksource import kSource
from kwave.ksensor import kSensor
from kwave.kspaceFirstOrder2D import kspaceFirstOrder2D
from kwave.options.simulation_options import SimulationOptions
from kwave.options.simulation_execution_options import SimulationExecutionOptions as ExecutionOptions
from kwave.utils.signals import tone_burst


# Parameters
steering_angle = np.arange(0, 1, 5)
n_steering_angle = len(steering_angle)

focus = 0e-3
focus_x = focus * np.cos(steering_angle * np.pi / 180)
focus_y = focus * np.sin(steering_angle * np.pi / 180)

# Initialize
source = kSource()
sensor = kSensor()

# Simulation settings
DATA_CAST = 'single'  # Use float32 for GPU computations

# Create the computational grid
ROIx = 120e-3  # ROI [m]
ROIy = 120e-3  # ROI [m]
PML_size = 100  # Size of the PML in grid points
Nx = 3000  # Number of grid points in the x (row) direction
Ny = 3000  # Number of grid points in the y (column) direction
dx = ROIx / Nx  # Grid point spacing in the x direction [m]
dy = ROIy / Ny  # Grid point spacing in the y direction [m]

kgrid = kWaveGrid(Vector([Nx, Ny]), Vector([dx, dy]))
f0 = 3.5e6  # Center frequency [Hz]

# Sensor
pitch = 0.25e-3  # Length between each sensor [m]
kerf = 0
N_active_tx = 80  # Number of elements of the transducer

# Vector
x = ((np.arange(Nx) - (Nx - 1) / 2) * dx)  # x-vector [m]
y = (np.arange(Ny) * dy)  # z-vector [m]

# Define the medium properties
c0_exact = 1540  # [m/s]
rho0 = 1000  # [kg/m^3]
rho = np.zeros((Nx, Ny)) + rho0
rho[Nx//2, Ny//2] = 1e12
alpha_coeff_exact = 0.5  # [dB/(MHz^y cm)]
lambda_wave = c0_exact / f0  # Wavelength [m]
medium = kWaveMedium(sound_speed=c0_exact, density=rho0, alpha_coeff=alpha_coeff_exact, alpha_power=1.5)


# Create the time array
t_end = (Nx * dx) / c0_exact /10 # [s] 
dt = 1 / 62.5e6 / 2  # Sampling time [s]
cfl = (dt * c0_exact / dx)  # Default: 0.3
kgrid.makeTime(c0_exact, cfl, t_end)

# Define a large image size to move across
Nx_tot = Nx
Ny_tot = Nx
ROIx_tot = Nx_tot * dx
ROIy_tot = Ny_tot * dy


# Define the input signal
source_strength = 1e1  # [Pa]
tone_burst_freq = f0  # [Hz]
tone_burst_cycles = 5  # 5 is optimum

# Source position
# center element at the center of the grid
el_pos_cart = np.column_stack((pitch * (np.arange(1, N_active_tx + 1) - (N_active_tx + 1) / 2), np.zeros(N_active_tx)))
pitch_n = round(pitch / dx)
from kwave.utils.matlab import rem
pitch_n_temp = pitch_n - 1 if not rem(pitch_n,  2) else pitch_n
rf_channel_data = np.zeros((n_steering_angle, N_active_tx, kgrid.Nt))

for n_input_signal in range(n_steering_angle):

    # Create the input signal using toneBurst
    num_elements = N_active_tx
    element_pos_x = el_pos_cart[:, 0]
    tone_burst_offset = element_pos_x* np.sin(steering_angle[n_input_signal] * np.pi / 180) / (c0_exact * dt)
    offset_time = np.min(tone_burst_offset)
    tone_burst_offset = np.round(-(offset_time) + tone_burst_offset)
    pulse_waveform = (source_strength / (c0_exact * rho0)) * tone_burst(1 / kgrid.dt, tone_burst_freq, tone_burst_cycles, signal_offset=tone_burst_offset.astype(np.int32), signal_length=kgrid.Nt)

    source.ux = np.empty((num_elements * pitch_n_temp, kgrid.Nt))
    source.u_mask = np.zeros((Nx, Ny))
    tx_apodization = np.ones(num_elements)

    # assign the input signal to all points of each element
    for n in range(N_active_tx):
        source_y_pos = round(Ny / 2) - round((pitch / ROIy * Ny) * ((N_active_tx + 1) / 2 - n))
        start_idx = round(source_y_pos - (pitch_n_temp - 1) / 2)
        stop_idx = round(source_y_pos + (pitch_n_temp - 1) / 2) + 1
        source.u_mask[0,start_idx : stop_idx] = 1
        source.ux[n * pitch_n_temp:(n+1) * pitch_n_temp, :] = np.tile(tx_apodization[n] * pulse_waveform[n], (pitch_n_temp, 1))

    # Run the simulation
    sensor.mask = np.ones((Nx, Ny), dtype=bool)
    # record the pressure
    sensor.record = ["p"]

    simulation_options = SimulationOptions(pml_inside=False, pml_size=PML_size, data_cast=DATA_CAST, save_to_disk=True, data_recast=True)
    sensor_data = kspaceFirstOrder2D(kgrid=kgrid, medium=medium, source=source, sensor=sensor, simulation_options=simulation_options, execution_options=ExecutionOptions(is_gpu_simulation=True))
    p_sensor_data = sensor_data['p']

    # Converting sensor data to channel data
    for tx_idx in range(N_active_tx):
        rf_channel_data[n_input_signal, tx_idx, :] = np.sum(p_sensor_data[:, pitch_n_temp * tx_idx: pitch_n_temp * (tx_idx + 1)], axis=1)


save_path = 'rf_channel_data_tot.npy'
np.save(save_path, rf_channel_data)

```

I hope this helps,
Walter

**Comment by waltsims** [comment]
Closing for now since we are moving the conversation to discord  and fix is merged.

**Comment by waltsims** [comment]
Here is the [link](https://discord.gg/Yq5Qj6D9vN)
