### ISSUE TITLE
check_stability behavior mismatch between Matlab and Python [BUG]

### ISSUE THREAD

**Issue by lewisfish** [waltsims/k-wave-python#421]
**Describe the bug**
I'm translating [this](https://github.com/sitiny/BRIC_TUS_Simulation_Tools/blob/main/tussim_skull_3D.m) to use Python k-wave.
I noticed that the check_stability does not match the behaviour of the Matlab version of k-wave. Namely that by default no_dispersion and no_absorption are the default options in the Matlab version but the not in the Python version. This leads to different values of dt.

**To Reproduce**
Run check_stability on Matlab and on Python and check the results of the function.

**Expected behavior**
The behaviors to match between Matlab and Python.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

Apologies if this is not a bug, I'm new to k-wave and acoustinc simulations in general.

**Comment by waltsims** [comment]
Hey @lewisfish,

Happy to look into this. It would be very helpful if you could share a minimal failing example in python with its equal in matlab.

Thanks,
Walter

**Comment by lewisfish** [comment]
Hi Walter,

Thank you for your speedy response.
Please find an attempt at a minimal example [here](https://gist.github.com/lewisfish/4cb9ebfa77cad42d8ee328450aeb2926).

If you comment out the checks for medium.alpha_mode to force it to give a non-zero value for alpha_eta and alpha_tau (i.e both no_dispersion and no_absorption), python and matlab match.
I think this is due to the Matlab version defaulting to this behaviour if alpha_mode is not set. Whereas the opposite is true for python.

Best,
Lewis

**Comment by waltsims** [comment]
Thanks @lewisfish. I'll continue to look into this. I'll also add that there are behavioral differences in k-Wave (matlab) between binary execution and matlab execution that I have found to be undocumented. See #383.

**Comment by waltsims** [comment]
Hey @lewisfish, I have a fix. Just waiting for review. It will be in v0.3.4.

**Comment by lewisfish** [comment]
Thanks for you work on this, much appreciated!
