### ISSUE TITLE
Run bmode_reconstruction_error

### ISSUE THREAD

**Issue by lmonsterrr** [waltsims/k-wave-python#44]
Hi, I was trying to run the exmaple and installed the requirments yet.
After precomputation.
            sensor_data = kspaceFirstOrder3DG/3DC
raise error.
'Running on Windows and Mac is not implemented yet'
The version of python is 3.9.13. 
Thank you!

**Comment by lmonsterrr** [comment]
It must be implemented on Linux?

**Comment by waltsims** [comment]
Hello,

Yes you are currently correct, but this will not be the case in the next release. Both Windows and Mac support are planned. Window support was already merged into main in commit https://github.com/waltsims/k-wave-python/commit/a9f3e274f24076f43b94410865f3e1930a4eac27.

You can try to run your sims with the current state of main on windows, or wait for the next release for official support.

Best,
Walter

**Comment by lmonsterrr** [comment]
Thanks！

**Comment by waltsims** [comment]
With v0.2.1 Windows support has been added. MacOS support will likely come in v0.3.0.
