### ISSUE TITLE
ImportError: cannot import name 'ChannelData' from 'uff'

### ISSUE THREAD

**Issue by hhapk** [waltsims/k-wave-python#79]
I feel sorry to disturbe your work. Because I got a problem.  When I run bmode_reconstruction_example.py, there was interrruption.
![image](https://user-images.githubusercontent.com/59441535/209548427-a5494d90-95d9-43ae-bb38-31b5e52d5e56.png)
there are the packages:
![image](https://user-images.githubusercontent.com/59441535/209548744-f22570d5-94f4-4a55-a934-445fd94ea3f5.png)
![image](https://user-images.githubusercontent.com/59441535/209548754-43148da4-c1ad-4454-9ba7-a6d2118c9991.png)
I wonder the package uff is not from the command 'pip install uff'? 
Hope you can help me in your free time, thanks!

**Comment by faridyagubbayli** [comment]
Hi @hhapk, you're right! The UFF package we use in this project is different from the package you get by running `pip install`. You can find the correct package and installation instructions here: https://github.com/waltsims/uff.py

**Comment by waltsims** [comment]
This also might help https://github.com/waltsims/k-wave-python/issues/16#issuecomment-1175484551

**Comment by waltsims** [comment]
closing for now. Reopen if you need any further support!
