### ISSUE TITLE
Consider compiling kWave binaries from source

### ISSUE THREAD

**Issue by faridyagubbayli** [waltsims/k-wave-python#9]
Shipping kWave binaries with the package results in larger package sizes. As the kWave source code is under 1MB, it might better to compile kWave from scratch during installation. However, this might expand the dependency list. We should exemine the process and see if it is feasible to do.

**Comment by waltsims** [comment]
This would also allow us to support more advanced NVIDIA sm as mentioned in #11.

**Comment by waltsims** [comment]
[LLVMlite](https://github.com/numba/llvmlite/blob/main/setup.py) might be a good option for this.

**Comment by waltsims** [comment]
can likely be accomplished via a [build hook in hatch](https://hatch.pypa.io/latest/config/build/#build-hooks).

**Comment by waltsims** [comment]
closing for now.
